# Generated by Django 3.0.2 on 2020-01-07 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoursEra', '0004_auto_20200108_0020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, default='avatars/default_avatar', upload_to='avatars'),
        ),
    ]
