# Generated by Django 3.0.2 on 2020-01-13 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CoursEra', '0006_auto_20200108_0025'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': 'Курс', 'verbose_name_plural': 'Курсы'},
        ),
    ]
